defaults:
  - data_paths: default
  - map_config: vlmaps
  - params: default
  - _self_
nav:
  valid_range: 1
  vis: False
  tasks_per_scene: 20
# scene_id: [1, 2, 3, 4, 5, 6, 7, 8, 9]
#TODO 模拟导航时候的config
scene_id: 0
